version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - misspell
    - unconvert
    - gocritic
  settings:
    govet:
      disable:
        - shadow
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
  exclusions:
    generated: lax
    presets:
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - gocritic
