version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - misspell
    - unconvert
    - gocritic
  exclusions:
    generated: lax
    test: lax

settings:
  govet:
    disable:
      - shadow
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
